Add changelog entry for dropping activesupport dependency
jaredbeck/paper_trail-sinatra pull request #12
Opened 2020-04-22 10:15 UTC by azgul

Missed adding it in https://github.com/paper-trail-gem/paper_trail-sinatra/pull/11

2020-04-22 10:18 UTC, azgul commented
A colleague of mine pointed out that I'd never added it. Somehow I had the changes staged and never committed/pushed them. Sorry.

Can I do anything to get this released?

2020-04-22 17:54 UTC, jaredbeck requested changes

2020-04-22 17:54 UTC, jaredbeck commented on CHANGELOG.md
> +- Drop `activesupport` dependency. Implicitly introduces `activerecord` 6.0 support
```suggestion
- [#11](https://github.com/paper-trail-gem/paper_trail-sinatra/pull/11) - Drop 
  `activesupport` dependency, thus allowing `activerecord` 6.0
```

2020-04-23 17:17 UTC, merged

2020-04-23 17:19 UTC, jaredbeck commented
@jkowens Jordan, can you cut a release please?

2020-04-23 18:08 UTC, jkowens commented
@jaredbeck I don't have permission to push to rubygems.

2020-04-23 18:18 UTC, jaredbeck commented
> I don't have permission to push to rubygems.

Oh, sorry. Can you please confirm that your rubygems account has MFA turned on, and then I'll add you (your public GH email, `jordan@copyandcode.com`) as a "gem owner".

2020-04-23 18:34 UTC, jkowens commented
I have 2FA enabled, but I just updated my public GH email to jkowens@gmail.com

2020-04-23 18:41 UTC, jaredbeck commented
```
gem owner paper_trail-sinatra --add 'jkowens@gmail.com'
Owner added successfully.
```

Thanks Jordan! Let me know if you have any questions about doing a release. Usually it involves updating:

1. `lib/paper_trail/sinatra/version.rb`,
1. the changelog, 
1. sometimes the readme

2020-04-23 18:52 UTC, jkowens commented
v0.7.0 has been released!